# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lu1582je-s/Project/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/lu1582je-s/Project/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/komponenter/SR4.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/komponenter/MUX2x8.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/cpu_pkg.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/komponenter/REG8.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/stack.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/komponenter/REG6.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/komponenter/MUX3x6.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/registerblock.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/komponenter/ALU8.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/misc/sub10.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/adressvaljare.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/instruktionsavkodare.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/berakningsenhet.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/misc/nbcd.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/misc/BCD_driver.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/misc/debouncer.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/misc/edge_det.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/misc/clk_divider.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/debugmodul.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/minne.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/IOblock.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/cpu.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/misc/reset_block.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/klockblock.vhd
  C:/Users/lu1582je-s/Project/project_1/project_1.srcs/sources_1/imports/MCU/labbfiler/mcu.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lu1582je-s/Project/project_1/project_1.srcs/constrs_1/imports/misc/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/lu1582je-s/Project/project_1/project_1.srcs/constrs_1/imports/misc/Nexys4_Master.xdc]


synth_design -top mcu -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mcu.dcp

catch { report_utilization -file mcu_utilization_synth.rpt -pb mcu_utilization_synth.pb }
